[package]
name = "ruff_python_literal"
version = "0.0.0"
publish = false
description = "Common literal handling utilities mostly useful for unparse and repr."
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>", "RustPython Team"]
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
bitflags = { workspace = true }
hexf-parse = { workspace = true }
is-macro = { workspace = true }
itertools = { workspace = true }
lexical-parse-float = { workspace = true, features = ["format"] }
unic-ucd-category = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
