[package]
name = "ruff_python_literal"
version = "0.0.0"
publish = false
description = "Common literal handling utilities mostly useful for unparse and repr."
authors = ["Charlie Marsh <charlie.r.marsh@gmail.com>", "RustPython Team"]
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]
doctest = false

[dependencies]
ruff_python_ast = { workspace = true }

bitflags = { workspace = true }
itertools = { workspace = true }
unic-ucd-category = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
