fail_fast: true

exclude: |
  (?x)^(
    crates/ruff/resources/.*|
    crates/ruff/src/rules/.*/snapshots/.*|
    crates/ruff_cli/resources/.*|
    crates/ruff_python_formatter/resources/.*|
    crates/ruff_python_formatter/tests/snapshots/.*|
    crates/ruff_python_resolver/resources/.*|
    crates/ruff_python_resolver/tests/snapshots/.*
  )$

repos:
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.12.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-black
          - black==23.1.0 # Must be the latest version of Black

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix

  - repo: https://github.com/crate-ci/typos
    rev: v1.14.12
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [ rust ]
        pass_filenames: false # This makes it a lot faster
      - id: ruff
        name: ruff
        entry: cargo run --bin ruff -- check --no-cache --force-exclude --fix --exit-non-zero-on-fix
        language: system
        types_or: [ python, pyi ]
        require_serial: true
        exclude: |
          (?x)^(
            crates/ruff/resources/.*|
            crates/ruff_python_formatter/resources/.*
          )$

  # Black
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

ci:
  skip: [ cargo-fmt, dev-generate-all ]
