[files]
# https://github.com/crate-ci/typos/issues/868
extend-exclude = [
    "crates/red_knot_vendored/vendor/**/*",
    "**/resources/**/*",
    "**/snapshots/**/*",
]

[default.extend-words]
"arange" = "arange"  # e.g. `numpy.arange`
hel = "hel"
whos = "whos"
spawnve = "spawnve"
ned = "ned"
pn = "pn"  # `import panel as pn` is a thing
poit = "poit"
BA = "BA" # acronym for "Bad Allowed", used in testing.
jod = "jod" # e.g., `jod-thread`
Numer = "Numer" # Library name 'NumerBlox' in "Who's Using Ruff?"

[default]
extend-ignore-re = [
    # Line ignore with trailing "spellchecker:disable-line"
    "(?Rm)^.*#\\s*spellchecker:disable-line$",
    "LICENSEs",
    # Various third party dependencies uses `typ` as struct field names (e.g., lsp_types::LogMessageParams)
    "typ",
    # TODO: Remove this once the `TYP` redirects are removed from `rule_redirects.rs`
    "TYP",
]

[default.extend-identifiers]
"FrIeNdLy" = "FrIeNdLy"
