[files]
# https://github.com/crate-ci/typos/issues/868
extend-exclude = ["crates/ruff_vendored/vendor/**/*", "**/resources/**/*", "**/snapshots/**/*"]

[default.extend-words]
"arange" = "arange"  # e.g. `numpy.arange`
hel = "hel"
whos = "whos"
spawnve = "spawnve"
ned = "ned"
pn = "pn"  # `import panel as pn` is a thing
poit = "poit"
BA = "BA" # acronym for "Bad Allowed", used in testing.
jod = "jod" # e.g., `jod-thread`

[default]
extend-ignore-re = [
  # Line ignore with trailing "spellchecker:disable-line"
  "(?Rm)^.*#\\s*spellchecker:disable-line$",
  "LICENSEs",
]
