[package]
name = "ruff_source_file"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]

[dependencies]
ruff_text_size = { workspace = true }

get-size2 = { workspace = true, optional = true }
memchr = { workspace = true }
serde = { workspace = true, optional = true }

[dev-dependencies]

[features]
get-size = ["dep:get-size2", "ruff_text_size/get-size"]
serde = ["dep:serde", "ruff_text_size/serde"]

[lints]
workspace = true
