[package]
name = "ruff_macros"
version = "0.0.244"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
once_cell = { version = "1.17.0" }
proc-macro2 = { version = "1.0.47" }
quote = { version = "1.0.21" }
syn = { version = "1.0.103", features = ["derive", "parsing", "extra-traits"] }
textwrap = { version = "0.16.0" }
itertools = { version = "0.10.5" }
