[package]
name = "ruff_diagnostics"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]

[dependencies]
ruff_python_ast = { path = "../ruff_python_ast" }

rustpython-parser = { workspace = true }
serde = { workspace = true, optional = true, default_features = false, features = [
] }
