[package]
name = "ruff_diagnostics"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
ruff_python_ast = { path = "../ruff_python_ast" }
ruff_text_size = { workspace = true }

rustpython-parser = { workspace = true }
serde = { workspace = true, optional = true, features = [] }
