[package]
name = "rustpython-compiler-core"
description = "RustPython specific bytecode."
version = "0.2.0"
authors = ["RustPython Team"]
edition = "2021"
repository = "https://github.com/RustPython/RustPython"
license = "MIT"

[dependencies]
bincode = "1.3.3"
bitflags = "1.3.2"
bstr = "0.2.17"
itertools = "0.10.3"
lz4_flex = "0.9.2"
num-bigint = { version = "0.4.3", features = ["serde"] }
num-complex = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.136", features = ["derive"] }
static_assertions = "1.1.0"
thiserror = "1.0"
