[package]
name = "ruff_python_ast"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]

[dependencies]
ruff_text_size = { workspace = true }

anyhow = { workspace = true }
bitflags = { workspace = true }
is-macro = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
memchr = { workspace = true }
num-bigint = { version = "0.4.3" }
num-traits = { version = "0.2.15" }
once_cell = { workspace = true }
rustc-hash = { workspace = true }
rustpython-literal = { workspace = true }
rustpython-parser = { workspace = true }
rustpython-ast = { workspace = true }
serde = { workspace = true, optional = true }
smallvec = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[features]
serde = ["dep:serde", "ruff_text_size/serde"]
