[package]
name = "ruff_python_ast"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[lib]

[dependencies]
ruff_rustpython = { path = "../ruff_rustpython" }
ruff_text_size = { workspace = true, features = ["serde"] }

anyhow = { workspace = true }
bitflags = { workspace = true }
memchr = "2.5.0"
is-macro = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num-bigint = { version = "0.4.3" }
num-traits = { version = "0.2.15" }
once_cell = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
rustpython-common = { workspace = true }
rustpython-parser = { workspace = true }
serde = { workspace = true, optional = true }
smallvec = { workspace = true }
