[tool.poetry]
name = "scripts"
version = "0.5.1"
description = ""
authors = ["Charles Marsh <charlie.r.marsh@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
autoflake = "*"
autopep8 = "*"
black = "*"
flake8 = "*"
isort = "*"
pycodestyle = "*"
pyflakes = "*"
pylint = "*"
yapf = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
formatter = [
  "black",
  "yapf",
  "autopep8",
]
linter = [
  "autoflake",
  "flake8",
  "pycodestyle",
  "pyflakes",
  "pylint",
  "isort",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
