[package]
name = "ruff_text_size"
version = "0.0.0"
publish = false
edition = "2021"
rust-version = "1.67.1"

[dependencies]
serde = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }

[dev-dependencies]
serde_test = { workspace = true }
static_assertions = { workspace = true }

[features]
serde = ["dep:serde"]

[lints]
workspace = true

[[test]]
name = "serde"
path = "tests/serde.rs"
required-features = ["serde"]
