[package]
name = "ruff_python_formatter"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
ruff_formatter = { path = "../ruff_formatter" }
ruff_python_whitespace = { path = "../ruff_python_whitespace" }
ruff_python_ast = { path = "../ruff_python_ast" }
ruff_text_size = { workspace = true }

anyhow = { workspace = true }
bitflags = { workspace = true }
clap = { workspace = true }
countme = "3.0.1"
is-macro = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rustc-hash = { workspace = true }
rustpython-parser = { workspace = true }
serde = { workspace = true, optional = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ruff_formatter = { path = "../ruff_formatter", features = ["serde"]}

insta = { workspace = true, features = ["glob"] }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }

[[test]]
name = "ruff_python_formatter_fixtures"
path = "tests/fixtures.rs"
test = true
required-features = [ "serde" ]


[features]
serde = ["dep:serde", "ruff_formatter/serde"]
default = ["serde"]
