[package]
name = "ruff_python_formatter"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ruff_formatter = { path = "../ruff_formatter" }
ruff_newlines = { path = "../ruff_newlines" }
ruff_python_ast = { path = "../ruff_python_ast" }
ruff_text_size = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
countme = "3.0.1"
is-macro = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rustc-hash = { workspace = true }
rustpython-parser = { workspace = true }

[dev-dependencies]
ruff_testing_macros = { path = "../ruff_testing_macros" }

insta = { workspace = true, features = [] }
test-case = { workspace = true }
similar = { workspace = true }
