[package]
name = "ruff_cache"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
itertools = { workspace = true }
glob = { workspace = true }
globset = { workspace = true }
regex = { workspace = true }
filetime = { workspace = true }
seahash = { workspace = true }

[dev-dependencies]
ruff_macros = { path = "../ruff_macros" }

[lints]
workspace = true
