[package]
name = "ruff_python_trivia"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[lib]

[dependencies]
ruff_text_size = { path = "../ruff_text_size" }
ruff_source_file = { path = "../ruff_source_file" }

itertools = { workspace = true }
unicode-ident = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
ruff_python_ast = { path = "../ruff_python_ast" }
ruff_python_parser = { path = "../ruff_python_parser" }
ruff_python_index = { path = "../ruff_python_index" }

[lints]
workspace = true
