[package]
name = "ruff_markdown"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
insta.workspace = true
regex.workspace = true
ruff_python_ast.workspace = true
ruff_python_formatter.workspace = true
ruff_python_trivia.workspace = true
ruff_workspace.workspace = true

[lints]
workspace = true
