[package]
name = "ruff_markdown"
version = "0.0.0"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[dependencies]
ruff_python_ast = { workspace = true }
ruff_python_formatter = { workspace = true }
ruff_python_trivia = { workspace = true }
ruff_source_file = { workspace = true }
ruff_text_size = { workspace = true }
ruff_workspace = { workspace = true }

regex = { workspace = true }

[dev-dependencies]
ruff_linter = { workspace = true }

insta = { workspace = true }

[lints]
workspace = true
