[package]
name = "ty_completion_bench"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
ruff_db = { workspace = true, features = ["os"] }
ruff_text_size = { workspace = true }

ty_ide = { workspace = true }
ty_project = { workspace = true }

anyhow = { workspace = true }
bstr = { workspace = true }
clap = { workspace = true, features = ["wrap_help", "string", "env"] }

[lints]
workspace = true
