[package]
name = "ty_wasm"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
description = "WebAssembly bindings for ty"

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[features]
default = ["console_error_panic_hook"]

[dependencies]
ty_ide = { workspace = true }
ty_project = { workspace = true, default-features = false, features = [
    "deflate",
    "format"
] }
ty_python_semantic = { workspace = true }

ruff_db = { workspace = true, default-features = false, features = [] }
ruff_diagnostics = { workspace = true }
ruff_notebook = { workspace = true }
ruff_python_formatter = { workspace = true }
ruff_source_file = { workspace = true }
ruff_text_size = { workspace = true }

console_error_panic_hook = { workspace = true, optional = true }
console_log = { workspace = true }
js-sys = { workspace = true }
log = { workspace = true }
# Not a direct dependency but required to enable the `wasm_js` feature.
# See https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { workspace = true, features = ["wasm_js"] }
serde-wasm-bindgen = { workspace = true }
tracing = { workspace = true, features = ["log"] }
# Not a direct dependency but required to compile for Wasm.
uuid = { workspace = true, features = ["js"] }

wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-shear]
# Depended on only to enable `log` feature as of 2025-10-03.
ignored = ["tracing"]
