[tool.ruff]
select = ["ALL"]
ignore = [
  "E501",    # line-too-long
  "INP001",  # implicit-namespace-package
  "PLR2004", # magic-value-comparison
  "S101",    # assert-used
  "EM"
]

[tool.ruff.pydocstyle]
convention = "pep257"
