[project]
name = "scripts"
version = "0.0.1"
dependencies = ["sphinx"]

[tool.ruff]
select = ["ALL"]
ignore = [
  "E501",   # line-too-long
  "INP001", # implicit-namespace-package
  "PL",     # pylint
  "S101",   # assert-used
  "EM",     # errmgs
  "D202",   # no-blank-line-after-function
]
unfixable = [
  "F841",   # unused-variable
  "RUF100", # unused-noqa
]

[tool.ruff.pydocstyle]
convention = "pep257"
