[package]
name = "ruff_dev"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
libcst = { workspace = true }
once_cell = { workspace = true }
pretty_assertions = { version = "1.3.0" }
regex = { workspace = true }
ruff = { path = "../ruff" }
ruff_cli = { path = "../ruff_cli" }
rustpython-common = { workspace = true }
rustpython-parser = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
textwrap = { workspace = true }
