[package]
name = "ruff_dev"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ruff = { path = "../ruff", features = ["schemars"] }
ruff_cli = { path = "../ruff_cli" }
ruff_diagnostics = { path = "../ruff_diagnostics" }
ruff_textwrap = { path = "../ruff_textwrap" }

anyhow = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
libcst = { workspace = true }
once_cell = { workspace = true }
pretty_assertions = { version = "1.3.0" }
regex = { workspace = true }
rustpython-format = { workspace = true }
rustpython-parser = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
